### ISSUE TITLE
Allow running the container on hosts with ipv6 disabled

### ISSUE THREAD

**Issue by Hudater** [modem7/docker-rickroll#19]
You get this error if the host has ipv6 disabled`nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)`

**Comment by modem7** [comment]
Looks like you've disabled ipv6 on your system.

You should be able to get this resolved by following the guidelines here to modify the nginx-site.conf file (you may need to mount your own (let me know if you need help with that)):

https://techglimpse.com/nginx-error-address-family-solution/#:~:text=Solution%3A%20The%20error%20message%20indicates,IPv4%20address%20as%20shown%20below.

That, or re-enable ipv6 on your system (you don't actually have to use ipv6).

**Comment by Hudater** [comment]
But modifying the nginx config requires access to the container's filesystem which I don't have since it exits on startup. Is there any other way to modify config without forking the repo?

**Comment by Hudater** [comment]
Ok I got it working with docker cp `https://stackoverflow.com/a/50166314`. Closing the issue

**Comment by modem7** [comment]
@Hudater There's another way to do this as well in case you want to modify it further later down the line: 

Mounting the file locally into the container via `volumes`:

```
  rickroll:
    image: modem7/docker-rickroll
    container_name: Rickroll
    ports:
      - 6519:80
    networks:
      pihole:
    volumes:
      - $USERDIR/rickroll/nginx-site.conf:/etc/nginx/conf.d/default.conf
```

with the content of nginx-site-conf:
```
server {
        listen   80; ## listen for ipv4; this line is default and implied
        listen   8080; ## listen for ipv4; this line is default and implied
        #listen   [::]:80 default ipv6only=on; ## listen for ipv6

        root /usr/share/nginx/html;
        index index.html;

        # Make site accessible from http://localhost/
        server_name _;

        error_page 404 /index.html;

        location /healthz {
                return 200;
        }

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to index.html
                try_files $uri =404;
        }


        location ~* \.(jpg|jpeg|gif|png|css|js|ico|webp|tiff|ttf|svg|mp4)$ {
                expires 5d;
        }
}
```

**Comment by Hudater** [comment]
I tried mounting / directly to a directory but failed so I'm using sed to remove 4th line from nginx.conf after `docker cp`. Janky solution but good enough for now

**Comment by modem7** [comment]
@Hudater could you try one thing for me please? 

See if `listen   [::]:80 default; ## listen for ipv6` works for you? (not having the ipv6only option on)

If it does, I'll rebuild all the images with that option and hopefully not have others come across this.

**Comment by Hudater** [comment]
same error 
```
2022/04/29 11:42:56 [emerg] 1#1: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
```

**Comment by modem7** [comment]
Alrighty - I'll have a think about the best solution moving forwards. 

I've also been wanting to modify the container so it doesn't run as root. Leave it with me, and I'll see what I can do. 

I'll re-open this issue in the meantime, so I have visibility and don't forget.

**Comment by Hudater** [comment]
I was searching for a solution to this issue so it will listen on both ipv4 and ipv6 and just ignore ipv6 if disabled on host. Found this thread which might be of help `https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/1743592`

**Comment by modem7** [comment]
OK, 

I think I've come up with a suitable solution. 

I need some time to implement it, and I'll spin up a test image. 

Are you running on x86 or something different like ARM?

**Comment by Hudater** [comment]
arm64 for this container

**Comment by modem7** [comment]
@Hudater could you try this image for me please?

```
  rickroll:
    image: modem7/docker-rickroll:iptest
    container_name: Rickroll
    ports:
      - 6519:8080
```

**Comment by modem7** [comment]
@Hudater Could you try the below please?

```
  rickroll:
    image: modem7/docker-rickroll:iptest
    container_name: Rickroll
    ports:
      - 6519:8080
```
