### ISSUE TITLE
Change Exposed Port

### ISSUE THREAD

**Issue by ghost** [modem7/docker-rickroll#49]
I am not sure where to ask this, here, reddit, discord etc. I love the project! However when I switch the port from 8080 to 7979 I receive a Cloudflare 502 error. I am also using Cloudflare Tunnels. The thought is rickroll.tld.com as URL. However I cant seem to figure it out. I am very much new at this and not sure if I am asking the correct question. I have port 8080 in use by another container, the reason I am trying to switch the port. Is someone able to point me in the correct direction? Thank you : )

**Comment by modem7** [comment]
Cheers! 

Do you have your compose file available?

**Comment by ghost** [comment]
wow mate, thank you, that was quick : ) I was just using the one you posted with the change to 7979.
`version: "2.4"

services:

  rickroll:
    image: modem7/docker-rickroll
    container_name: Rickroll
    ports:
      - 7979:8080
    environment:
      - TITLE="Rickroll" # Changes the title of the webpage`

**Comment by modem7** [comment]
That certainly looks alright, and as long as the left hand port reference doesn't clash with another container, you should be golden. 

However, if you wish to change the listening port of the container, rather than just the exposed port, you can do:

```yaml
  rickroll:
    image: modem7/docker-rickroll
    container_name: Rickroll
    ports:
      - 7979:7979
    environment:
      - TITLE="Rickroll" # Changes the title of the webpage
      - PORT=7979
```

This will then change the internal port used by NGINX as per: https://github.com/modem7/docker-rickroll/blob/ba010954be218c6cda3585a22eeb82433aea1de5/scripts/70-nginx.sh#L44
