### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by TechnoidAlpha** [modem7/docker-rickroll#59]
Hi, I am trying to run this beautiful app on my Truenas scale server. I've got external access through traefik and a cloudflare domain/dns setup however I keep getting this 500 error when visiting the site. Not sure if I am being inept and have something configured incorrectly.

Would normally ask this kind of question in a discord channel for the app/plugin but this plugin somehow doesn't have a community for it haha.
![image](https://github.com/modem7/docker-rickroll/assets/38853588/0dc5c87d-cb0e-4ad6-842a-5bab1d23d74f)

**Comment by modem7** [comment]
Heya, 

Could you show me your compose file?

Anything showing in the logs?

**Comment by modem7** [comment]
This is what I'm using w/ Traefik:

```yaml
  rickroll:
    image: modem7/docker-rickroll
    container_name: Rickroll
    ports:
      - 6519:8080
    networks:
      pihole:
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.rickrolltest-rtr.entrypoints=https"
      - "traefik.http.routers.rickrolltest-rtr.rule=Host(`rick.$DOMAINNAME`)"
      - "traefik.http.routers.rickrolltest-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.rickrolltest-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.rickrolltest-rtr.service=rickrolltest-svc"
      - "traefik.http.services.rickrolltest-svc.loadbalancer.server.port=8080"
```
